### ISSUE TITLE
Okan Review - Task 2

### ISSUE THREAD

**Issue by okandavutosf** [danielvigaru/reactjs-internship#1]
I will take look after you add this items:

- For inputs buttons and modal we want you to use React-Bootstrap please change with it.
- And i couldnt see your user-informations.json file ?

After you added this items i will take a look detailly.

**Comment by danielvigaru** [comment]
The JSON is in the public directory. I've put it there so I can fetch it.
https://www.pluralsight.com/guides/fetch-data-from-a-json-file-in-a-react-app

I will look up how to use bootstrap and make changes accordingly.

**Comment by okandavutosf** [comment]
I dont mean use Boostrap i mean use React-Bootstrap library. 

Check documents in here delete your css code and use directly inputs and buttons from here : 

https://react-bootstrap.github.io/components/input-group/

Also for popup please use in here.

**Comment by danielvigaru** [comment]
I think we had a little miscommunication, I did use react-bootstrap. Earlier I said bootstrap out of habit, sorry.
As you can see I've modified the input, the button and the alert created by me to their react-bootstrap counterparts, respectively `FormControl`, `Button` and `Alert`.

**Comment by okandavutosf** [comment]
Sorry thats my fault :) i didnt get latest version :) Checked now. 

Code seems fine. Small changes.

- Create components folder and get input, popup and Submit inside of it.

- Input.js -  Carry methods top below will be just return.

![image](https://user-images.githubusercontent.com/77776340/126005892-73f165af-bd36-40c7-8d18-f4aa2850a48e.png)


- Submit.js Please delete commented codes 

![image](https://user-images.githubusercontent.com/77776340/126006043-a87889b4-61b5-401c-af35-98ff5d533ba5.png)

**Comment by danielvigaru** [comment]
Done. I've also moved the JSON to `/src` and imported it instead of fetching it.
